version: "3"
services:
  app:
    container_name: unichat-deploy
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: deploy
    ports:
      - "80:8080"
    depends_on:
      - db
    command: ./main
    
  dev:
    container_name: unichat-develop
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
      target: devlop
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - ./backend:/app

  db:
    container_name: unichat-db
    build:
      context: ./backend
      dockerfile: Dockerfile.db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mydb
      MYSQL_USER: kazuki
      MYSQL_PASSWORD: secret
      TZ: Asia/Tokyo
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - type: volume
        source: unichat-volume
        target: /var/lib/mysql
volumes:
  unichat-volume:
    name: unichat-mysql